### ISSUE TITLE
No worky in Lightning :-(

### ISSUE THREAD

**Issue by tet3** [pcon/sfdc-sandboxVersion#1]
Which seems weird, since it's clearly the same page code. Maybe something to do with how it's iframed in?

![sandboxesinlex](https://user-images.githubusercontent.com/1319826/51933677-db8a7f00-23cf-11e9-8d60-51a62d7d3600.PNG)

**Comment by pcon** [comment]
Yep, that's next on my todo list to fix.  Going to work with someone this afternoon to fix.  I don't have access to a instance with lightning and sandboxes.

**Comment by pcon** [comment]
This is now working.  It'll take a little bit of time for the managed version to be updated on the store and in the browser.
