### ISSUE TITLE
Pending Sandbox breaks those below it in the list 

### ISSUE THREAD

**Issue by tet3** [pcon/sfdc-sandboxVersion#3]
This is **not** a big deal, but I noticed it, and so wanted to at least bring it to your attention.

**Describe the bug**
After you kick off a new sandbox creation (perhaps also a refresh?), the Sandboxes below the new, pending Sandbox no longer have the release icon and hover text.

**To Reproduce**
1.  Go to 'Setup > Sandboxes > New Sandbox'
2.  Enter a name that is alphabetically neither first nor last among your current Sandbox names. Click Next on an available license type, and continue through prompts to kick off Sandbox creation.
3.  Return to the Sandboxes list.
4.  Note that those Sandboxes below the now-pending Sandbox in the list don't have a release icon and no text appears when hovering mouse cursor to the left of the sandbox instance.

**Expected behavior**
All Sandboxes with a Sandbox instance listed will have a release icon and hover text.

**Screenshots**
![2019-05-20 18_38_52-Sandboxes _ Salesforce](https://user-images.githubusercontent.com/1319826/58056631-ccbb0a00-7b2f-11e9-9fe5-a917a46ca711.png)

**Comment by pcon** [comment]
I've seen this before with the lighting developer pro sandboxes. I'll get this fixed soon and let you know when it's been released

**Comment by pcon** [comment]
This is fixed in 1.1.1 and should now be available on all stores.

**Comment by tet3** [comment]
Ooh, I like the question mark/"Unknown" indicator! Thanks!
